// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz86Ho2dkIJbKucFy2cdjaAmRKkis2svg',
    appId: '1:727589976733:ios:3db618ca74b57977153274',
    messagingSenderId: '727589976733',
    projectId: 'breedr-3c5dc',
    storageBucket: 'breedr-3c5dc.firebasestorage.app',
    iosBundleId: 'com.example.breedr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IVpTazrtUjTnJo1qon0GJkIFisvdxa4',
    appId: '1:727589976733:web:910b1194dae46f8e153274',
    messagingSenderId: '727589976733',
    projectId: 'breedr-3c5dc',
    authDomain: 'breedr-3c5dc.firebaseapp.com',
    databaseURL: 'https://breedr-3c5dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedr-3c5dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqDn8anoYzrVLDe_9cDNdl1UG6Ymp-Qg',
    appId: '1:727589976733:android:08aed596ccf1922e153274',
    messagingSenderId: '727589976733',
    projectId: 'breedr-3c5dc',
    databaseURL: 'https://breedr-3c5dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedr-3c5dc.firebasestorage.app',
  );

}